name: CI

on: [push, pull_request, workflow_dispatch]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: taiki-e/checkout-action@3ab630d442e198ebb0ca30872832406ca01c46eb # v1.4.0
      - uses: oxc-project/setup-rust@704e1648ce532a12b4d6fb98db0ba10afa3ae879 # v1.0.13
        with:
          save-cache: ${{ github.ref_name == 'main' }}
          cache-key: warm
      - name: Check with no feature flags
        run: cargo check --verbose --no-default-features
        working-directory: ./schemars
      - name: Run tests
        run: cargo test --verbose --all-features --no-fail-fast
        working-directory: ./schemars
      - name: Run derive tests
        run: cargo test --verbose --all-features --no-fail-fast
        working-directory: ./schemars_derive
